apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cicd
  labels:
    app: kubernetes-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-cicd
  template:
    metadata:
      labels:
        app: kubernetes-cicd
    spec:
      containers:
      - name: kubernetes-cicd
        image: yuukiryusei/kubernetes-cicd:20250623
        ports:
        - containerPort: 80

